### ISSUE TITLE
add a requirements.txt like a gentleman

### ISSUE THREAD

**Issue by babycommando** [Sebby37/Dead-Internet#3]
haha this is neat, so  here's a tip for making running this project simpler:

add a requirements.txt to the root of this project with the following:

```
beautifulsoup4
openai
Flask
```

and change the readme.md for people to run:
```
pip install -r requirements.txt
```

nice job, ai friend

**Comment by Zetaphor** [comment]
See #4

**Comment by Sebby37** [comment]
Ask and ye shall receive
